### ISSUE TITLE
tesselation producing unexpected striation

### ISSUE THREAD

**Issue by knaaptime** [martinfleis/momepy#168]
hey @martinfleis thanks for putting this package together; its great. 

I wanted to give both this package and the new `pyrosm` a spin, just to get acquainted with both of them. Since pyrosm is so fast at parsing OSM, I wanted to use a relatively large area, so [here's](https://gist.github.com/knaaptime/1f1a323ad08bd1cbe7347efb65e74bd2) a shot at doing a morphological tesselation for all the buildings in the District of Columbia, just following the `momepy` guide. Most of the results look perfect, but there are a handful of these oddly striped polygons:

<img width="565" alt="Screen Shot 2020-05-07 at 5 36 36 PM" src="https://user-images.githubusercontent.com/4213368/81358360-21ca9580-908b-11ea-9460-b287792ef96c.png">

![image](https://user-images.githubusercontent.com/4213368/81358353-1aa38780-908b-11ea-95f1-0b7884dbdd63.png)

Any idea why that's happening? Obviously it takes a while to run given the size of the area, so you can download the results pictured above [here](https://www.dropbox.com/s/b7vawupvibp1y1g/dc.zip?dl=0) if you want.

**Comment by martinfleis** [comment]
Hi, this is caused by overlapping building polygons. See the example from your data below.

I have just added [`momepy.CheckTessellationInput`](http://docs.momepy.org/en/latest/generated/momepy.CheckTessellationInput.html#momepy.CheckTessellationInput), which does a check for these kinds of issues before tessellation and identifies those polygons which may (but not always will) cause an issue (_I should fix docstring typos_).

I don't think there is a way how to avoid this within tessellation, the data just need to be clean.

You also got the warning in the end of Tessellation in your gist `UserWarning: Tessellation contains MultiPolygon elements. Initial objects should be edited. unique_id of affected elements: [33, 251,...` pointing directly to most of those faulty cells.

![Snímek obrazovky 2020-05-08 v 9 35 31](https://user-images.githubusercontent.com/36797143/81387830-4405f700-910f-11ea-98d1-c330844795b1.png)

**Comment by knaaptime** [comment]
thanks! I noticed that warning, and figured it was likely related, but when I checked those UIDs against the polys i posted above, it didnt seem to be in there. I think in haste I was looking at the UID of the *resulting* poly rather than the two overlapping inputs. Oops. Anyway, thanks for the detailed and prompt response. Much appreciated.
